channels:
  - conda-forge
  - defaults

dependencies:
  - jupyter
  - ipywidgets
  - numpy < 2

  - torchvision
  - torchmetrics
  - pytorch-lightning

  - setuptools
  - lightning

  - matplotlib
  - seaborn

  - transformers
  - datasets
  - accelerate
  - bitsandbytes